version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: swatantrakumarthakuar/swatantra-portfolio:latest # Change this to your-dockerhub-username/swatantra-portfolio:latest before pushing
    container_name: swatantra_portfolio
    ports:
      - "8080:80"
    restart: unless-stopped
